name: Deploy to GitHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate module files
        run: node server.js

      - name: Upload generated files to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: generated-modules
          path: ./public/*.sgmodule  

      - name: Push to repository
        run: |
          git config --local user.email "your-email@example.com" 
          git config --local user.name "Your Name"  
          git add ./public/*.sgmodule
          git commit -m "Update generated module files"
          git push origin main
