name: generate_desc

on:
  push:
    branches:
      - main
    paths:
      - 'qx/**'
      - 'loon/**'
      - 'surge/**'
      - 'stash/**'
  workflow_dispatch:

jobs:
  update-comments:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9' 

    - name: Run script
      run: python .github/scripts/generate_desc.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check for changes
      id: check_changes
      run: |
        git status
        git diff-index --quiet HEAD || echo "::set-output name=changes_exist::true"
    
    - name: Commit and push if changes exist
      if: steps.check_changes.outputs.changes_exist == 'true'
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add -A
        git commit -m "Automated comments update for files" -a || exit 0 
        git push origin HEAD:main --force
