name: Generate sgmodule

on:
  push:
    paths:
      - '.github/scripts/**' # Trigger on changes in .github/scripts folder
  workflow_dispatch:

jobs:
  generate_sgmodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Run script
        run: python .github/scripts/generate_sgmodule.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
